//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achivement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Achivement()
        {
            this.AchivementStudent = new HashSet<AchivementStudent>();
        }
    
        public int idAchivement { get; set; }
        public int idJournal { get; set; }
        public int idTypeEvent { get; set; }
        public string fullNameSupervis { get; set; }
        public string topicWork { get; set; }
        public System.DateTime dateEvent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchivementStudent> AchivementStudent { get; set; }
        public virtual Journal Journal { get; set; }
        public virtual TypeOfEvent TypeOfEvent { get; set; }
    }
}
