//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendance()
        {
            this.LackAttendance = new HashSet<LackAttendance>();
        }
    
        public int idAttendance { get; set; }
        public int idJournal { get; set; }
        public System.DateTime dateAttendance { get; set; }
        public int idDiscipline { get; set; }
        public int idOccupStat { get; set; }
        public string fullNameTeach { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Journal Journal { get; set; }
        public virtual OccupationStatus OccupationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LackAttendance> LackAttendance { get; set; }
    }
}
