//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;

    public partial class Curator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curator()
        {
            this.Journal = new HashSet<Journal>();
        }

        public int idCurator { get; set; }
        public string surnameCurator { get; set; }
        public string nameCurator { get; set; }
        public string patronymicCurator { get; set; }
        public string positionCurator { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string question { get; set; }
        public string ansver { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journal { get; set; }
        public override string ToString() => surnameCurator + " "+ nameCurator + " " + patronymicCurator;
    }
}
