//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int idFamily { get; set; }
        public int idStudent { get; set; }
        public string fullNameSpous { get; set; }
        public Nullable<bool> statusSpous { get; set; }
        public string professionSpous { get; set; }
        public string nameChild { get; set; }
        public Nullable<System.DateTime> dateOfBirthChild { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
