//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinalGrade()
        {
            this.ListMarkStud = new HashSet<ListMarkStud>();
        }
    
        public int idFinalGrade { get; set; }
        public int idDiscipline { get; set; }
        public int idFormContr { get; set; }
        public int SemesterDis { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual FormOfControl FormOfControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListMarkStud> ListMarkStud { get; set; }
    }
}
