//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalStudent
    {
        public int idStudent { get; set; }
        public int idJournal { get; set; }
        public Nullable<bool> stipendSemOne { get; set; }
        public Nullable<bool> stipendSemTwo { get; set; }
        public Nullable<int> idStatusSt { get; set; }
        public int idJournalStudent { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual StatusStudent StatusStudent { get; set; }
        public virtual Student Student { get; set; }
    }
}
