//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kin()
        {
            this.TalkParents = new HashSet<TalkParents>();
        }
    
        public int idKin { get; set; }
        public string fullNameKin { get; set; }
        public string kinStatus { get; set; }
        public string telephoneKin { get; set; }
        public Nullable<bool> disabilityKin { get; set; }
        public string placeOfWorkKin { get; set; }
        public Nullable<int> idStudent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalkParents> TalkParents { get; set; }
        public virtual Student Student { get; set; }
    }
}
