//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMarkStud
    {
        public int idListMarkStudent { get; set; }
        public int idStudent { get; set; }
        public int idFinalGrade { get; set; }
        public int idGrade { get; set; }
    
        public virtual FinalGrade FinalGrade { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Student Student { get; set; }
    }
}
