//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.LackMeeting = new HashSet<LackMeeting>();
        }
    
        public int idMeeting { get; set; }
        public int idJournal { get; set; }
        public System.DateTime dateMeeting { get; set; }
        public bool statusMeeting { get; set; }
        public bool typeMeeting { get; set; }
        public string questionMeeting { get; set; }
        public string decisionMeeting { get; set; }
    
        public virtual Journal Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LackMeeting> LackMeeting { get; set; }
    }
}
