//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingMark
    {
        public int idRatingMark { get; set; }
        public int idStudent { get; set; }
        public int idDiscipline { get; set; }
        public int idRating { get; set; }
        public int ratingMark1 { get; set; }
        public int idJournal { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Journal Journal { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Student Student { get; set; }
    }
}
