//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residence()
        {
            this.Student = new HashSet<Student>();
            this.Student1 = new HashSet<Student>();
        }
    
        public int idResidence { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string town { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string korpus { get; set; }
        public string flat { get; set; }
        public Nullable<int> idHostel { get; set; }
        public string room { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student1 { get; set; }
    }
}
