//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AchivementStudent = new HashSet<AchivementStudent>();
            this.Family = new HashSet<Family>();
            this.JournalStudent = new HashSet<JournalStudent>();
            this.Kin = new HashSet<Kin>();
            this.LackAttendance = new HashSet<LackAttendance>();
            this.LackMeeting = new HashSet<LackMeeting>();
            this.ListMarkStud = new HashSet<ListMarkStud>();
            this.PrivTalkStudent = new HashSet<PrivTalkStudent>();
            this.RatingMark = new HashSet<RatingMark>();
        }
    
        public int idStudent { get; set; }
        public int idGroup { get; set; }
        public string surnameStudent { get; set; }
        public string nameStudent { get; set; }
        public string patronymicStudent { get; set; }
        public bool formOfTrainStudent { get; set; }
        public System.DateTime dateOfBirthStudent { get; set; }
        public string telephoneStudent { get; set; }
        public bool disabilityStudent { get; set; }
        public int idForeignLangStudent { get; set; }
        public string nameSchoolStudent { get; set; }
        public System.DateTime yearOfManStudent { get; set; }
        public int idResidencePerman { get; set; }
        public Nullable<int> idResidenceTemp { get; set; }
        public bool gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchivementStudent> AchivementStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Family { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalStudent> JournalStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kin> Kin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LackAttendance> LackAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LackMeeting> LackMeeting { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListMarkStud> ListMarkStud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivTalkStudent> PrivTalkStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingMark> RatingMark { get; set; }
        public virtual Residence Residence { get; set; }
        public virtual Residence Residence1 { get; set; }
        public override string ToString() => surnameStudent + " " + nameStudent;
    }
}
