//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyingProcess
    {
        public int idStudyingProcess { get; set; }
        public int idJournal { get; set; }
        public int semester { get; set; }
        public System.DateTime semesterStart { get; set; }
        public System.DateTime semesterEnd { get; set; }
        public System.DateTime sessionStart { get; set; }
        public System.DateTime sessionEnd { get; set; }
        public Nullable<System.DateTime> practiceProductStart { get; set; }
        public Nullable<System.DateTime> practiceProductEnd { get; set; }
        public Nullable<System.DateTime> practiceTrainStart { get; set; }
        public Nullable<System.DateTime> practiceTrainEnd { get; set; }
        public System.DateTime holidaysStart { get; set; }
        public System.DateTime holidaysEnd { get; set; }
    
        public virtual Journal Journal { get; set; }
    }
}
