//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalkParents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalkParents()
        {
            this.StructParentsTalc = new HashSet<StructParentsTalc>();
        }
    
        public int idTalkPar { get; set; }
        public int idTopTPar { get; set; }
        public int idJournal { get; set; }
        public string topicTalc { get; set; }
        public System.DateTime dateTalkPar { get; set; }
    
        public virtual Journal Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructParentsTalc> StructParentsTalc { get; set; }
        public virtual TopicTalkParents TopicTalkParents { get; set; }
    }
}
